sudo: required
services:
    - docker

before_install:
    - docker build -t jdtcoder/client -f ./client/Dockerfile.dev ./client

script:
    - docker run jdtcoder/client npm run test -- --coverage

after_success:
    - docker build -t jdtcoder/complex-client ./client
    - docker build -t jdtcoder/complex-nginx ./nginx
    - docker build -t jdtcoder/complex-server ./server
    - docker build -t jdtcoder/complex-worker ./worker
    # login to the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take those images and push to docker hub
    - docker push jdtcoder/complex-client
    - docker push jdtcoder/complex-nginx
    - docker push jdtcoder/complex-server
    - docker push jdtcoder/complex-worker
# deploy:
#     provider: elasticbeanstalk
#     region: "us-east-2"
#     app: "docker-react"
#     env: "DockerReact-env"
#     bucket_name: "elasticbeanstalk-us-east-2-462173466510"
#     bucket_path: "docker-react"
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key:
#         secure: "$AWS_SECRET_KEY"
